version: "3"
services:
  otel-collector:
    build:
      context: ../..
      dockerfile: examples/tracing/Dockerfile
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1777:1777"   # pprof extension
      - "8887:8888"   # Prometheus metrics exposed by the agent
      - "14268"       # Jaeger receiver
      - "55678:55678" # OpenCensus receiver
      - "55679:55679" # zpages extension
      - "13133"       # health_check
